POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "c7ce4127-afea-47f6-9126-ed22a6dac0bd"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "4ba94984-d733-41be-8a22-aae5052d6b1a",
    "account_id_to": "3506c046-f344-4eae-b18a-ca0b3b40666f",
    "amount": 1
}
